const CardsActionTypes = {
  FETCH_CARDS_START: "FETCH_CARDS_START",
  FETCH_CARDS_SUCCESS: "FETCH_CARDS_SUCCESS",
  FETCH_CARDS_FAILURE: "FETCH_CARDS_FAILURE",
  LOAD_CARDS_START: "LOAD_CARDS_START",
  LOAD_CARDS_SUCCESS: "LOAD_CARDS_SUCCESS",
  LOAD_CARDS_FAILURE: "LOAD_CARDS_FAILURE",
};

export default CardsActionTypes;
