const CardsActionTypes = {
  FETCH_CARDS_START: "FETCH_CARDS_START",
  FETCH_CARDS_SUCCESS: "FETCH_CARDS_SUCCESS",
  FETCH_CARDS_FAILURE: "FETCH_CARDS_FAILURE",
  FETCH_STATS_START: "FETCH_STATS_START",
  FETCH_STATS_SUCCESS: "FETCH_STATS_SUCCESS",
  FETCH_STATS_FAILURE: "FETCH_STATS_FAILURE",
  FETCH_ADD_OFFSET: "FETCH_ADD_OFFSET",
};

export default CardsActionTypes;
