const FavsActionTypes = {
  FETCH_FAVS_ITEMS_START: "FETCH_FAV_ITEMS_START",
  FETCH_FAVS_ITEMS_SUCCESS: "FETCH_FAV_ITEMS_SUCCESS",
  FETCH_FAVS_ITEMS_FAILURE: "FETCH_FAV_ITEMS_FAILURE",
  ADD_FAV_START: "ADD_FAV_START",
  ADD_FAV_SUCCESS: "ADD_FAV_SUCCESS",
  ADD_FAV_FAILURE: "ADD_FAV_FAILURE",
  ADD_FAV_LOCAL: "ADD_FAV_LOCAL",
  DELETE_FAV_START: "DELETE_FAV_START",
  DELETE_FAV_SUCCESS: "DELETE_FAV_SUCCESS",
  DELETE_FAV_FAILURE: "DELETE_FAV_FAILURE",
  DELETE_FAV_LOCAL: "DELETE_FAV_LOCAL",
  CLEAR_FAVS: "CLEAR_FAVS",
};

export default FavsActionTypes;
