const FavsActionTypes = {
  ADD_FAV: "ADD_FAV",
  REMOVE_FAV: "REMOVE_FAV",
  CLEAR_FAVS: "CLEAR_FAVS",
  FETCH_FAVS_ITEMS_START: "FETCH_FAV_ITEMS_START",
  FETCH_FAVS_ITEMS_SUCCESS: "FETCH_FAV_ITEMS_SUCCESS",
  FETCH_FAVS_ITEMS_FAILURE: "FETCH_FAV_ITEMS_FAILURE",
};

export default FavsActionTypes;
